name: "Test devcontainer features"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - chezmoi
          - clojure
          - puppet
          - rbw
          - restish
    steps:
      - uses: actions/checkout@v4

      - name: "Install devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Test ${{ matrix.features }}"
        run: devcontainer features test -f ${{ matrix.features }}
